build-sravan:
  stage: build
  script:
    - echo "this is message from STAGE"


test-job:
  stage: test
  script:
    - echo "this is message from TEST"

deploy-job:
  stage: deploy
  script:
    - echo "this is message from Deplyed on AWS EKS cluster"